services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/conf.d/mailparse.ini:/usr/local/etc/php/conf.d/mailparse.ini